# Dataset paths and parameters
data:
  csv_file: "filtered_train.csv"
  cif_directory: "/lustre07/scratch/jabou/models/CGCNN-np"
  ionic_conductivity_column: "Ionic conductivity (S cm-1)"

# Graph settings
graph:
  cutoff: 5.0
  threebody_cutoff: 5.0

# Dataset splitting
split:
  k_folds: 5
  shuffle: True
  random_state: 42

# DataLoader settings
dataloader:
  batch_size: 50
  num_workers: 0

# Model parameters
model:
  is_intensive: True
  readout_type: "set2set"

# Training parameters
training:
  lr: 0.001
  max_epochs: 100
  accelerator: "gpu"
  log_every_n_steps: 1

# Logger settings
logger:
  save_dir: "logs"
  name: "M3GNet_training"

# Plot settings
plot:
  fig_size: [10, 6]
  dpi: 300

# Output settings
output:
  metrics_file: "metrics.csv"
  results_csv: "cross_validation_results.csv"
  raw_data_dir: "./dgl"
