# Dataset paths and parameters
seed: 10  

data:
  csv_train_file: "filtered_train.csv"  
  csv_test_file: "filtered_test.csv"    
  cif_directory: "cif"  
  ionic_conductivity_column: "Ionic conductivity (S cm-1)"  

# Graph settings
graph:
  cutoff: 5.0
  threebody_cutoff: 5.0

# Dataset splitting (for cross-validation)
split:
  k_folds: 5         
  shuffle: True      
  random_state: 42   

# DataLoader settings
dataloader:
  num_workers: 0     

# Model parameters for M3GNet
m3gnet:
  is_intensive: True
  readout_type: ["set2set", "weighted_atom", "reduce_atom"]
  nblocks: [2, 3, 4]
  dim_node_embedding: [32, 64, 128]
  dim_edge_embedding: [32, 64, 128]
  units: [32, 64, 128]
  threebody_cutoff: [4.0, 5.0, 6.0]
  cutoff: [4.0, 5.0, 6.0]

# Model parameters for SO3Net
so3net:
  is_intensive: True
  target_property: "graph"
  readout_type: ["set2set", "weighted_atom", "reduce_atom"]
  nmax: [1, 2, 3]
  lmax: [1]
  nblocks: [2, 3, 4]
  dim_node_embedding: [32, 64, 128]
  units: [32, 64, 128]
  cutoff: [4.0, 5.0, 6.0]
  nlayers_readout: [3, 4, 5]

# Hyperparameter tuning space (for grid search)
hyperparameters:
  num_cases: 100  
  batch_size: [32]  
  lr: [0.0005, 0.001, 0.01]  
  max_epochs: [35, 60, 80]  

# Training parameters
training:
  accelerator: "gpu"  

# Logger settings
logger:
  save_dir: "logs"       
  name: "Model_training" 

# Plot settings
plot:
  fig_size: [10, 6]   
  dpi: 300            

# Output settings
output:
  metrics_file: "metrics.csv"         
  results_csv: "cross_validation_results.csv"  
  raw_data_dir_train: "./dgl_train"   
  raw_data_dir_test: "./dgl_test"     


pretrained_model_dir: "/pretrained_model"
