seed: 10

# File and directory paths
runtime_files:
  - './split.npz'
  - './splitting.lock'
  
database_path: '../../../data/processed.csv'
test_path: '../../../test_idx.csv'
cif_file_dir: '../../../data/np_cifs'
overwrite_db: False
db_dir: '.'
extra_plots: True
show: True

# Data processing parameters
representation: "painn"
file_prefix: 'train'
remove_mean: true
remove_atomrefs: false
cutoff: [5, 10]
n_atom_basis: [20, 40]
n_interactions: 3
batch_size: 203
n_train_data: 10
num_folds: 2
n_param_combs: 100
actual_list: [runtime_files]

# CIF file reading parameters
cif_read_options:
  index: -1
  store_tags: false
  primitive_cell: false
  subtrans_included: true
  fractional_occupancies: true
  reader: 'ase'

# Number of workers and memory handling
num_workers: 4
pin_memory: false

# Trainer configurations
max_epochs: 3
learning_rate: 0.01
weight_decay: 0

# Logging and checkpoint paths
out_dir: 'painn'

# Plot settings
high_dpi: 300

# Metrics settings
monitor_metric: 'val_loss'
save_top_k: 1
